apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: redhat-canada
  namespace: cluster-config
spec:
  type: GitHub
  pathname: https://github.com/redhat-canada-gitops/catalog.git