apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators
  annotations:
    apps.open-cluster-management.io/github-path: /jaeger-operator/overlays/default
    apps.open-cluster-management.io/github-branch: master
  labels:
    app: operators
spec:
  channel: cluster-config/redhat-canada
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters