apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: openshift-operators
spec:
  # Deploy to dev clusters
  clusterSelector:
    matchLabels:
      environment: dev