apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-config
  namespace: cluster-config
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: cluster-config