apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: cluster-config
  namespace: cluster-config
spec:
  type: GitHub
  pathname: https://github.com/gnunn1/cluster-config-new.git