 apiVersion: apps.open-cluster-management.io/v1
 kind: Subscription
 metadata:
   name: sealed-secrets
   annotations:
    apps.open-cluster-management.io/github-path: /manifests/apps/sealed-secrets/base
    apps.open-cluster-management.io/github-branch: master
 spec:
  channel: cluster-config/cluster-config
  placement:
    placementRef:
      kind: PlacementRule
      name: all-clusters